# Usar NGINX como servidor web (versión ligera Alpine)
FROM nginx:alpine

# Copiar nuestro HTML al directorio por defecto de NGINX
COPY index.html /usr/share/nginx/html/index.html

# Exponer el puerto 80 (el puerto estándar de NGINX)
EXPOSE 80
