version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fredy}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secreto123}
      POSTGRES_DB: ${POSTGRES_DB:-miapp}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db # ¡Aquí está la magia! Docker resuelve 'db' a la IP del contenedor
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
