services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: fredy
      POSTGRES_PASSWORD: secreto123
      POSTGRES_DB: miapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # ¡Esto guarda los datos aunque apagues el contenedor!

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_USER: fredy
      POSTGRES_PASSWORD: secreto123
      POSTGRES_DB: miapp
      POSTGRES_HOST: db # ¡Aquí está la magia! Docker resuelve 'db' a la IP del contenedor de la BD
    depends_on:
      - db # Le dice a Docker: "Prende la BD antes que el backend"

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata: # Declaramos el volumen para que los datos persistan
